### ISSUE TITLE
groups of circuit

### ISSUE THREAD

**Issue by darkdragon-001** [mredaelli/circuitikz#6]
There should be an easy way to group some elements together (e.g. draw circle around them) and then name this group. Helpful for bigger circuits!

Just like the "Part 1" in the attached image!

![image](https://f.cloud.github.com/assets/177976/579875/6a379aba-c87a-11e2-8bc3-77b254e0285b.png)

**Comment by mredaelli** [comment]
Just two years too late...

I agree, but 1) you are basically asking for the bounding box of a series of nodes, which is something that should be offered, if at all, by TikZ itself; 2) I doubt there's a robust way to do it in general.
