### ISSUE TITLE
bipolar capacitors

### ISSUE THREAD

**Issue by darkdragon-001** [mredaelli/circuitikz#7]
Bipolar capacitors like the following one should be added:

![image](http://www.jnsforum.com/community/uploads/gallery/album_45/med_gallery_459_45_1357005302_1301.jpg)

**Comment by sistlind** [comment]
done, see last commit.
Up to now, the starting point of the symbol will be always the plus pole, but I will try to implement an option "reverse" to rotate the symbol

**Comment by darkdragon-001** [comment]
@sistlind Thank you very much!

Btw: You can reference a commit (via SHA bbb898b) or direclty close it from within a commit message (see https://help.github.com/articles/closing-issues-via-commit-messages/).
